### ISSUE TITLE
How to run this program?

### ISSUE THREAD

**Issue by tonyho** [eagleEggs/topanga#2]
Hi, thanks for you wonderful project. I want to try to run it, but I it fails:
```
 python3 _testAnatomy.py 
Traceback (most recent call last):
  File "_testAnatomy.py", line 32, in <module>
    import TA_Changelog
ModuleNotFoundError: No module named 'TA_Changelog'
```

Can you give a hint to run it?
Thanks.

**Comment by eagleEggs** [comment]
Hi @tonyho apologies but I did not see this message. This repository was used as a kind of a storage spot for some of the code but it is not organized enough to run, and I haven't given any explanation as to how to run it. There have been a lot of updates since two years ago that haven't been pushed here. Soon I may update this repository with the new code and write up a decent readme to enable others to run it. Thanks for your interest in it.

**Comment by mjheydari** [comment]
> Hi, thanks for you wonderful project. I want to try to run it, but I it fails:
> 
> ```
>  python3 _testAnatomy.py 
> Traceback (most recent call last):
>   File "_testAnatomy.py", line 32, in <module>
>     import TA_Changelog
> ModuleNotFoundError: No module named 'TA_Changelog'
> ```
> 
> Can you give a hint to run it? Thanks.

Hello,
you can comment this line because TA_Changlog not use in code

**Comment by eagleEggs** [comment]
Will be working on packaging this up and will leave this open until then.

Is anyone using this though? If so I'll try to get it out sooner.
